__default__:
  time: 0-02:00:00
  job-name:  maplnc_def
  ntasks: 1
  cpus-per-task: 12
  mem-per-cpu: 8G
  partition: vfast
  working-directory: /gscratch/debbiarm/atlas/logs

get_ids:
  job-name: getids
  time: 0-00:10:00

download_sra:
  job-name: down_sra
  time: 0-10:00:00
  mem-per-cpu: 8G
  partition: p_fast
cutadapt_trim_reads:
  job-name: cutadapt
  time: 0-03:00:00
  cpus-per-task: 8
build_star_index:
  job-name: starindex
  time: 0-02:00:00
star_map:
  job-name: star
  time: 0-02:00:00
transcriptome_assembly_stringtie:
  job-name: stringtie
  time: 0-4:00:00
merge_samples:
  job-name: stringmerge
build_transcriptome:
  job-name: gffread
  time: 0-02:00:00
download_sra_quant:
  job-name: down_sra2
  time: 0-15:00:00
  mem-per-cpu: 8G
  partition: p_fast
cutadapt_trim_reads_quant:
  job-name: cut_quant
  time: 0-03:00:00
  cpus-per-task: 8
kallisto_index:
  job-name: kall_idx
  time: 0-03:00:00
quantify_kallisto:
  job-name: kallisto
  time: 0-03:00:00
  mem-per-cpu: 8G
  cpus-per-task: 8
quantify_kallisto_un:
  job-name: kallisto
  time: 0-03:00:00
  mem-per-cpu: 8G
  cpus-per-task: 8
merge_kallisto_output:
  job-name: mergecounts